### Arrays
### Arrays are R objects that are able to store data in multiple dimensions.
#### example: ex_array <- array(data=c(1,2,3), dim=c(1,2,2))
#### Characteristics:
#### 1. take vectors as inputs
#### 2. Dim argument controls the dimension
#### 3. With c(1,2,2) we create 2 matrices with 1 row by 2 columns
#### 4. every position in the dim corresponds to its dimension.
#### 5. you can use dim names to name elements in the array.
#### 6. they hold elements of the same type. !important!

### Creating arrays

<p>Transform a vector into an array.</p>

In [2]:
my_vect <- 1:4

my_array <- array(data=my_vect, dim=c(2,2))

my_array

[,1] [,2]
[1,] 1    3   
[2,] 2    4

<p>To index on array, 1st row = 1st element of dimension. The sequence is row, column. Since we want the entire row we leave the second space after the comma blank.</p>

In [3]:
my_array[1,]

[1] 1 3

<p>Lets get the first 2nd column valus in the first row. You can see above that value = 3.</p>

In [4]:
my_array[1,2]

[1] 3

<p>Get the 2nd row - We only change the 1st value to 2.</p>

In [6]:
my_array[2,]

[1] 2 4

<p>Check the dimensions of the array. Thi sone is 2 by 2, represented by 2 columns and 2 rows.</p>

In [7]:
dim(my_array)

[1] 2 2

###  Indexing and modifying arrays

In [9]:
# create a new array with additional dimensions.
# notice the array will repeat the sequence of 1-8 becaseu we are usng a 4 by 4 dim.
my_array <- array(1:8, dim = c(4,4))

my_array

[,1] [,2] [,3] [,4]
[1,] 1    5    1    5   
[2,] 2    6    2    6   
[3,] 3    7    3    7   
[4,] 4    8    4    8

<p>Extract 4th column, this produces all elements from the 4 dims.</p>

In [10]:
my_array[,4]

[1] 5 6 7 8

<p>Get 2nd and 3rd elements from 3rd col</p>

In [11]:
my_array[2:3,3]

[1] 2 3

<p>Get the 3rd row.</p>

In [13]:
my_array[3,]

[1] 3 7 3 7

### Modify Elements

<p>Change the column value by assigning a vector of new elements to the first column.</p>

In [14]:
my_array[,1] <- c(100, 100, 100, 100)

my_array

[,1] [,2] [,3] [,4]
[1,] 100  5    1    5   
[2,] 100  6    2    6   
[3,] 100  7    3    7   
[4,] 100  8    4    8

<p>Change the row values for the 1st 2 rows.</p>

In [15]:
my_array[1:2,] <- array(c(1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000), dim = c(2,4))

my_array

[,1] [,2] [,3] [,4]
[1,] 1000 1000 1000 1000
[2,] 1000 1000 1000 1000
[3,]  100    7    3    7
[4,]  100    8    4    8

### Array Operations

In [32]:
my_array <- array(data = c(100, 100, 100), dim = c(3,3,2))

my_array

, , 1

     [,1] [,2] [,3]
[1,]  100  100  100
[2,]  100  100  100
[3,]  100  100  100

, , 2

     [,1] [,2] [,3]
[1,]  100  100  100
[2,]  100  100  100
[3,]  100  100  100

<p>Changes 1st array to a sq rt of 100, see the diff in 1 & 2</p>

In [33]:
# array 1
my_array[,,1]<- sqrt(my_array[,,1])

my_array[,,1]

[,1] [,2] [,3]
[1,] 10   10   10  
[2,] 10   10   10  
[3,] 10   10   10

In [34]:
# array 2
my_array[,2,]

[,1] [,2]
[1,] 10   100 
[2,] 10   100 
[3,] 10   100

<p>Apply a power to the 2nd element of both objects</p>

In [35]:
my_array[,2,]<-my_array[,2,]**2

my_array[,1,]
my_array[,2,]

[,1] [,2]
[1,] 10   100 
[2,] 10   100 
[3,] 10   100

[,1] [,2] 
[1,] 100  10000
[2,] 100  10000
[3,] 100  10000

In [36]:
# change one specific element by dividing by 5
# 1st dim, 3rd col, 2nd array
my_array[1,3,2]


my_array[1,3,2]<-my_array[1,3,2]/5

my_array 

[1] 100

, , 1

     [,1] [,2] [,3]
[1,]   10  100   10
[2,]   10  100   10
[3,]   10  100   10

, , 2

     [,1]  [,2] [,3]
[1,]  100 10000   20
[2,]  100 10000  100
[3,]  100 10000  100

### Dim names property

<p>Add names as index to grab data.</p>

In [37]:
countries_data<-array(c(200,200,300,340,230,120,540,400), 
                      dim=c(2,2,2), dimnames = list(c('Portugal', 'UK'), 
                                                    c('Population', 'GDP'),
                                                    c('2018', '2019')))
countries_data

, , 2018

         Population GDP
Portugal        200 300
UK              200 340

, , 2019

         Population GDP
Portugal        230 540
UK              120 400

In [38]:
# we can use the names as indexes
countries_data['Portugal', 'Population', '2019']

[1] 230

In [39]:
# get both years by adding a vector
countries_data['Portugal', 'Population', c('2018', '2019')]

2018 2019 
 200  230

In [41]:
# change a dimname
dimnames(countries_data)[[1]]<-c('Portugal', 'Spain')

countries_data

, , 2018

         Population GDP
Portugal        200 300
Spain           200 340

, , 2019

         Population GDP
Portugal        230 540
Spain           120 400

In [42]:
# get the number of rows using nrows
nrow(countries_data)

[1] 2

In [43]:
# get no of cols
ncol(countries_data)

[1] 2

### Combining Arrays

In [44]:
# rows or cols
my_array_1<-array(c(1:4), dim<-c(2,2))

my_array_1

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [45]:
# create another array
my_array_2<-array(c(10:14), dim<-c(2,2))

my_array_2

[,1] [,2]
[1,] 10   12  
[2,] 11   13

In [46]:
# to append, on eon top of another-mut have the same shape!!!
rbind(my_array_1, my_array_2)

[,1] [,2]
[1,]  1    3  
[2,]  2    4  
[3,] 10   12  
[4,] 11   13

In [47]:
#to combine side by side
cbind(my_array_1, my_array_2)

[,1] [,2] [,3] [,4]
[1,] 1    3    10   12  
[2,] 2    4    11   13

### Challenges:

#### 1. Create an array called fourdim and feed it with the data 1:10. Your array must have 2 elements on each dimension.

#### 2. Set the [2,2,2,2] element on the fourdim array to NA

#### 3. Extract the mean of the fourdim array - pay attention to the NA's.

#### 4. Create an array called threed with three dimensions with 3 elements in the first, 2 in the second and 2 in the third. Name your first dimension as "Stock Price", "Revenue", "Employees", the second as "2018","2019" and the third as "Apple","Microsoft". Feed the array with the following data:  (155, 261, 132000,423.4, 321, 137000,105, 240, 118000,157.64, 260, 139000)


#### 5. Using array indexes, compute the difference between Apple's stock price in 2019 and 2018. Store it in an object called diff_price.

#### 6. Based on the diff_price object, compute percentage difference (in decimal format, where for instance: 0.5 equals to 50%) between Apple's stock price in 2019 and 2018. Use array indexes again to find the 2018 Apple stock price in the 3-d array.

#### 7. Extract all the information that you have for Apple on 3-D array. Remember, 'Apple' is on the third dimension. Store it in an object called apple.

#### 8. Extract every "Stock Price" that we have on our array. Remember, "Stock Price" is on the first dimension. Store it in an object called stock_price.
