### Matrices

<p>Essentially, these are two dimensional arrays.</p>

In [1]:
# for help - ?matrix()
example_matrix1 <- matrix(data=1:4, nrow=10, ncol=4)

example_matrix1

[,1] [,2] [,3] [,4]
 [1,] 1    3    1    3   
 [2,] 2    4    2    4   
 [3,] 3    1    3    1   
 [4,] 4    2    4    2   
 [5,] 1    3    1    3   
 [6,] 2    4    2    4   
 [7,] 3    1    3    1   
 [8,] 4    2    4    2   
 [9,] 1    3    1    3   
[10,] 2    4    2    4

In [2]:
# The data is input vertically by column, 
# to alter this so its input row by row use byrow = TRUE in the ()
example_matrix <- matrix(data=1:4, nrow=10, ncol=4, byrow = TRUE)
example_matrix

[,1] [,2] [,3] [,4]
 [1,] 1    2    3    4   
 [2,] 1    2    3    4   
 [3,] 1    2    3    4   
 [4,] 1    2    3    4   
 [5,] 1    2    3    4   
 [6,] 1    2    3    4   
 [7,] 1    2    3    4   
 [8,] 1    2    3    4   
 [9,] 1    2    3    4   
[10,] 1    2    3    4

In [3]:
# create the 1st matrix using an array
example_matrix2 <- array(data = 1:4, dim = c(10,4))

example_matrix2 == example_matrix1

[,1] [,2] [,3] [,4]
 [1,] TRUE TRUE TRUE TRUE
 [2,] TRUE TRUE TRUE TRUE
 [3,] TRUE TRUE TRUE TRUE
 [4,] TRUE TRUE TRUE TRUE
 [5,] TRUE TRUE TRUE TRUE
 [6,] TRUE TRUE TRUE TRUE
 [7,] TRUE TRUE TRUE TRUE
 [8,] TRUE TRUE TRUE TRUE
 [9,] TRUE TRUE TRUE TRUE
[10,] TRUE TRUE TRUE TRUE

In [4]:
dim(example_matrix2)

[1] 10  4

In [5]:
class(example_matrix2)

[1] "matrix"

In [6]:
ncol(example_matrix2)

[1] 4

### Matrix Operations

In [8]:
example_matrix1 <- matrix(data = 1:4, nrow = 2, ncol = 2)
example_matrix1


example_matrix2 <- matrix(data = 200:203, nrow = 2, ncol = 2)
example_matrix2

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] 200  202 
[2,] 201  203

In [9]:
# * multiply by one another
# you can also use +, -, /, **
example_matrix1 * example_matrix2

[,1] [,2]
[1,] 200  606 
[2,] 402  812

In [10]:
# DOT Product of a matrix (simple algebra)
matrix1 <-matrix(1:6, nrow = 2, ncol=3, byrow = TRUE)

matrix1

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [11]:
matrix2 <-matrix(7:12, nrow = 3, ncol=2, byrow = TRUE)
matrix2

[,1] [,2]
[1,]  7    8  
[2,]  9   10  
[3,] 11   12

In [12]:
# HOW CAN WE MULTIPLY MATRIX1 BY MATRIX2 TO GET THE DOT PRODUCT?
# USE %*%, inner dims must match!
matrix1 %*% matrix2

[,1] [,2]
[1,]  58   64 
[2,] 139  154

### Challenges:

#### 1.Create a matrix using the matrix() function with 3 rows and 2 columns - name it matrix_example. Feed it with the following data: c(100,23,42,23,342,203)

In [14]:
# Solution
matrix_example <- matrix(data = c(100,23,42,23,342,203), nrow = 3, ncol = 2)
matrix_example

[,1] [,2]
[1,] 100   23 
[2,]  23  342 
[3,]  42  203

#### 2. Divide the whole matrix by itself and store it in an object called one_matrix.

In [15]:
# Solution
one_matrix <- matrix_example/matrix_example

one_matrix

[,1] [,2]
[1,] 1    1   
[2,] 1    1   
[3,] 1    1

#### 3. Apply a logarithm to the first column of the matrix. Rewrite that column in the one_matrix.

#### 4. Multiply the second row of the matrix by 0.33 - rewrite the row on the one_matrix.

#### 5. Transpose the one_matrix and save it in an object called one_matrix_t.

#### 6. Use matrix multiplication properties to compute the multiplication of matrix_example and one_matrix_tand save it in an object called matrix_mul. Hint: Remember the %*% operator.